application: laureate-playlist-jea
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /fonts
  static_dir: static/fonts

- url: /img
  static_dir: static/img

- url: /fancybox
  static_dir: static/fancybox

- url: /.*
  script: main.app
